### ISSUE TITLE
AccountVBox clickable area. 

### ISSUE THREAD

**Issue by Jefferson-Xie** [kchelvan/FinanceApp#3]
Right now you can click the area beneath the bottom most account and it will edit the account above it.
(https://cdn.discordapp.com/attachments/261320333208977419/689610110624202814/unknown.png)

**Comment by keshopan-uoit** [comment]
I've fixed this in my current branch. I will push the code once I finish my current bug as well.

**Comment by keshopan-uoit** [comment]
Solved.
