### ISSUE TITLE
Opening an Account after editing an account breaks page

### ISSUE THREAD

**Issue by keshopan-uoit** [kchelvan/FinanceApp#6]

**Comment by Jefferson-Xie** [comment]
It maybe that everything after editing an account breaks it. Just opening and then depositing/withdrawing works. But after editing, it no longer updates.

**Comment by keshopan-uoit** [comment]
Yeap, it was an issue that I found after the code refactor. I will take a look at it.

**Comment by keshopan-uoit** [comment]
Solved.
